package website

var holdTheLineList = []string{
	"/.env",
	"/.git",
	"/.gitignore",
	"/.git/config",
	"/actuator/health",
	"/remote/logincheck",
	"/api/v2/static/not.found",
	"/_ignition/execute-solution",
	"/download/file.ext",
	"/WuEL",
	"/mPlayer",
	"/SiteLoader",
	"/a",
	"/dns-query",
	"/wp-login.php",
	"/version",
	"/RDWeb",
	"/showLogin.cc",
	"/Remote",
	"/owa/auth/errorFE.aspx?httpCode=500",
	"/wsman",
	"/dana-cached/hc/HostCheckerInstaller.osx",
	"/dana-na/nc/nc_gina_ver.txt",
	"/ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application",
	"/api/sonicos/auth",
	"/auth1.html",
	"/api/sonicos/tfa",
	"/sslvpnLogin.html",
	"/owa/auth/logon.aspx",
	"/nice ports,/Trinity.txt.bak",
	"/geoserver/web/",
	"/api/opinion/index",
	"/ReportServer",
	"/.vscode/sftp.json",
	"/debug/default/view?panel=config",
	"/v2/_catalog",
	"/server-status",
	"/login.action",
	"/_all_dbs",
	"/.DS_Store",
	"/actuator/gateway/routes",
	"/xmlrpc.php?rsd",
	"/cms/wp-includes/wlwmanifest.xml",
	"/blog/wp-includes/wlwmanifest.xml",
}
