export const CHAIN_SEGMENT_DENSITY = 0.000001;
export const CLAW_DENSITY = 0.000001;
export const CREATURE_DENSITY = 0.000001;

export const CLAW_SEPERATOR_UPPER_MIN= 60, CLAW_SEPERATOR_UPPER_MAX= 80, 
             CLAW_SEPERATOR_LOWER_MIN= 10, CLAW_SEPERATOR_LOWER_MAX= 100;

export const CHAIN_MOVEMENT_DELTA = 100;
export const CHAIN_SEGMENT_SIZE = 10;

