export const CHAIN_SEGMENT_DENSITY = 0.005;
export const CLAW_DENSITY = 0.001;
export const CREATURE_DENSITY = 0.0001;

export const CLAW_SEPERATOR_UPPER_MIN= 80, CLAW_SEPERATOR_UPPER_MAX= 120, 
             CLAW_SEPERATOR_LOWER_MIN= -5, CLAW_SEPERATOR_LOWER_MAX= 140;

export const CHAIN_MOVEMENT_DELTA = 100;
export const CHAIN_SEGMENT_SIZE = 10;


export const CREATURE_SIZE_MIN = 14;
export const CREATURE_SIZE_MAX = 20;
export const CREATURE_COUNT_MAX = 2000;
export const CREATURE_SPAWN_TIME = 2000;
